import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { promises as fs } from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// 出力ディレクトリ
const outdir = '.';

// 出力フォルダが存在することを確認
await fs.mkdir(outdir, { recursive: true });

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(outdir, 'main.js'),
});

// ビルド後にmanifest.jsonとstyles.cssをdistフォルダにコピー
async function copyPluginFiles() {
	try {
		// manifest.jsonをコピー
		const manifestContent = await fs.readFile('./manifest.json', 'utf8');
		await fs.writeFile(path.join(outdir, 'manifest.json'), manifestContent);
		
		// styles.cssをコピー
		const stylesContent = await fs.readFile('./styles.css', 'utf8');
		await fs.writeFile(path.join(outdir, 'styles.css'), stylesContent);
		
		console.log(`✅ Plugin files copied to ${outdir}/`);
	} catch (error) {
		console.error('Error copying plugin files:', error.message);
	}
}

if (prod) {
	await context.rebuild();
	await copyPluginFiles();
	console.log(`✅ Build complete! Files are in ${outdir}/ directory`);
	process.exit(0);
} else {
	await context.watch();
	await copyPluginFiles();
}
